### Eigenvalues and Eigenvectors

Multiplication by a matrix is a linear tansformation that maps vectors (points) to different vectors(points).

But in special cases,  vectors will not change (except for scaling) when transformed.

An eigen vector $\vec{e}$ for a linear transformation represented by matrix $A$ will satisfy $A\vec{e} = \lambda \vec{e}$.

In other words, $A$ maps its eigenvector $\vec{e}$ to (a scaled version) of itself.

In [1]:
import torch
from torch import linalg as LA

# A = [cos(45)  sin(45)  0]
#     [-sin(45) cos(45)  0]
#     [0              0  1]
# This matrix performs a rotation about the Z axis [0  0  1].
# All rotation matrices have 1 as an eigen-value. The corresponding
# eigenvector will be the axis of rotation.
# This is consistent with the physical definition of rotation axis -
# that points on the axis stay where they were post the rotation.
A = torch.tensor([[0.7071, 0.7071, 0], [-0.7071, 0.7071, 0], [0, 0, 1]])

# LA.eig returns eigen values in the array l and the corresponding
# eigen vectors as columns of e.
# Note that eigen values can be complex numbers (with a real and
# imaginary part). The imaginary part will be expressed via
# j which denotes square root of -1 (imaginary number).
l, e = LA.eig(A)

print("Eigen values are\n{}\n".format(l))
print("Eigen vectors are\n{}\n\n"
      "Note that 1 + 0j i.e 1 is an Eigen value\n"
      "and [0, 0, 1+0j] i.e Z Axis is an Eigen vector.".format(e.T))

Eigen values are
tensor([0.7071+0.7071j, 0.7071-0.7071j, 1.0000+0.0000j])

Eigen vectors are
tensor([[0.7071+0.0000j, 0.0000+0.7071j, 0.0000+0.0000j],
        [0.7071-0.0000j, 0.0000-0.7071j, 0.0000-0.0000j],
        [0.0000+0.0000j, 0.0000+0.0000j, 1.0000+0.0000j]])

Note that 1 + 0j i.e 1 is an Eigen value
and [0, 0, 1+0j] i.e Z Axis is an Eigen vector.
