# 02 Image formation

In [9]:
import numpy as np
import math

In [20]:
s = math.pi
R = np.array([[math.cos(s), -math.sin(s)], [math.sin(s), math.cos(s)]])
print(R)
print(R.T)
print(R @ R.T)
print(R * R.T)

[[-1.0000000e+00 -1.2246468e-16]
 [ 1.2246468e-16 -1.0000000e+00]]
[[-1.0000000e+00  1.2246468e-16]
 [-1.2246468e-16 -1.0000000e+00]]
[[1. 0.]
 [0. 1.]]
[[ 1.00000000e+00 -1.49975978e-32]
 [-1.49975978e-32  1.00000000e+00]]
